### ISSUE TITLE
Logo's needed for App Store / app icon

### ISSUE THREAD

**Issue by garyjunior94** [MattDWhittle/rootlab-escan#3]
For iPads/App Store, square icons are needed and they need to be the following size

20x20 pixels
29x29 pixels
40x40 pixels
76x76 pixels
83.5x83.5 pixels
1024x1024 pixels

**Comment by Shasper** [comment]
Starting on this, what file type do they need, (jepg, png, etc..)?

**Comment by garyjunior94** [comment]
They should all be png

**Comment by Shasper** [comment]
I am not sure 20x20 px is right. our logo is indistinguishable at such a small size, what could we put here and what is it for? Here is our Logo at 20x20px 
![Root Lab PNG20x20](https://user-images.githubusercontent.com/50428918/57468670-c8dade00-7239-11e9-8e75-e54e248b60ce.png)

**Comment by garyjunior94** [comment]
They basically just have a bunch of different ones you have to replace for appstore, icon, etc... The one for 20x20 px it says is for ipad settings, which I don't image anyone needing to change or even ever see, so I'm sure that'll work just fine.

**Comment by Shasper** [comment]
how do i send these to you? Is there a place here i upload them?

**Comment by garyjunior94** [comment]
I think you can just attach files directly here to this ticket by dragging them onto a new comment. If that doesn't work, feel free to just email them and I can add them to the repository.

**Comment by Shasper** [comment]
![40x40logo](https://user-images.githubusercontent.com/50428918/57484204-511eaa80-725d-11e9-935f-fb35dabbb182.png)
![76x76logo](https://user-images.githubusercontent.com/50428918/57484205-51b74100-725d-11e9-9fbb-08da26032fc3.png)
![83x83logo](https://user-images.githubusercontent.com/50428918/57484206-51b74100-725d-11e9-8e47-55bf68307907.png)
![1024x1024logo](https://user-images.githubusercontent.com/50428918/57484207-51b74100-725d-11e9-8486-3b6727de65f6.png)
![20x20logo](https://user-images.githubusercontent.com/50428918/57484208-51b74100-725d-11e9-9c65-8090add47b23.png)
![29x29logo](https://user-images.githubusercontent.com/50428918/57484209-524fd780-725d-11e9-8076-1c5bbb373eae.png)

**Comment by Shasper** [comment]
Are you able to use these or do I need to send them a different way? I can also make some with a translucent background if there is a need.

**Comment by garyjunior94** [comment]
I can download them from here as png's so they should be ok, but I haven't been able to include them in the code yet.  I'll do that tonight and let you know.

**Comment by Shasper** [comment]
Got it. I will add a few things to the “issues” let me know if I am doing it wrong

**Comment by garyjunior94** [comment]
Added all the logos, they look great.  It's a bit tricky to make sure everything was properly submitted to Git when adding that kind of stuff, so let me know if you have any build failures when trying to run the app.
