### ISSUE TITLE
Forefoot Extension Headings

### ISSUE THREAD

**Issue by Shasper** [MattDWhittle/rootlab-escan#6]
Under Forefoot extension there are three scroll menus with the headings Extension Material, Extension Thickness, and Extension Length. Can the  the headings be static, maybe above the scrolls so that it is clear what you have changed?

**Comment by garyjunior94** [comment]
Static titles added above. Had to update the enable/disable behavior since 1 element was taken out of the picker, so let me know if that works well. I also made the pickers scroll to the top when selecting no top cover / orthotic only so that's in there now.
